---
# tasks file for control

#    Perform a dist-update and upgrade.

    - name: update apt
      apt: update_cache=yes

    - name: upgrade apt 
      apt: upgrade=dist force_apt_get=yes


    - name: Copy hosts file
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

    - name: Copy /usr/local/bin folder
      ansible.builtin.copy:
        src: /usr/local/bin/
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: '0755'


    - name: Install zerotier-one vpn
      apt:
        name: zerotier-one
        state: present 

    - name: install virtualization system
      ansible.builtin.apt:
        name: cpu-checker
        state: present

    - name: install qemu-kvm
      ansible.builtin.apt:
        name: qemu-kvm
        state: present

    - name: Copy /home/kevin/shellscripts/ folder
      ansible.builtin.copy:
        src: /home/kevin/shellscripts/
        dest: /home/kevin/shellscripts/
        owner: kevin
        group: kevin
        mode: '0755'

    - name: install libvirt-clients
      ansible.builtin.apt:
        name: libvirt-clients
        state: present 

    - name: install libvirt-daemon-system
      ansible.builtin.apt:
        name: libvirt-daemon-system
        state: present

    - name: install bridge-utils
      ansible.builtin.apt:
        name: bridge-utils
        state: present



#next,start the kvm services and enable 
#systemctl enable libvirtd
# systemctl start libvirtd
## but above state: present  . could be enough, since we do not want to auto start these services, only start manually when needed

# add your desired user to the KVM and libvirt groups:
# usermod -aG kvm $USER
# usermod -aG libvirt $USER


