---
# tasks file for control


    - name: Copy /usr/local/bin folder
      ansible.builtin.copy:
        src: /usr/local/bin/
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: '0755'


