---
# tasks file for common

#    Perform a dist-update and upgrade.

    - name: update apt
      apt: update_cache=yes

    - name: upgrade apt 
      apt: upgrade=dist force_apt_get=yes


    - name: Copy hosts file
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

    - name: Install zerotier-one vpn
      apt:
        name: zerotier-one
        state: present 

    - name: install virtualization system
      ansible.builtin.apt:
        name: cpu-checker
        state: present

    - name: install qemu-kvm
      ansible.builtin.apt:
        name: qemu-kvm
        state: present

    - name: Copy /home/kevin/shellscripts/ folder
      ansible.builtin.copy:
        src: /home/kevin/shellscripts/
        dest: /home/kevin/shellscripts/
        owner: kevin
        group: kevin
        mode: '0755'

    - name: install libvirt-clients
      ansible.builtin.apt:
        name: libvirt-clients
        state: present 

    - name: install libvirt-daemon-system
      ansible.builtin.apt:
        name: libvirt-daemon-system
        state: present

    - name: install bridge-utils
      ansible.builtin.apt:
        name: bridge-utils
        state: present
