- hosts: asusvpn
  gather_facts: 'yes'
  become: 'yes'
  tasks:
    - name: check nfs installed
      ansible.builtin.apt:
        name:
          - nfs-common
          - nfs4-acl-tools
        state: present

    - name: Mount an NFS volume
      ansible.posix.mount:
        src: kevinvm1vpn:/
        path: /media/kevin/KEVINVM1VPN
        opts: rw,sync,hard
        state: mounted
        fstype: nfs




