---
- hosts: all
  gather_facts: yes
  become: yes
  
  tasks: 


    - name: Copy /home/kevin/shellscripts/ folder 
      ansible.builtin.copy:
        src: /home/kevin/shellscripts/
        dest: /home/kevin/shellscripts/
        owner: kevin
        group: kevin
        mode: '0744'
