- hosts: all
  gather_facts: 'yes'
  become: 'yes'
  tasks:
    - name: Copy hosts file
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
    - name: Copy /usr/local/bin folder
      ansible.builtin.copy:
        src: /usr/local/bin/
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: '0644'

    - name: Install zerotier-one vpn
      ansible.builtin.apt:
        name: zerotier
        state: present 

    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: 'yes'
    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: 'no'
      register: reboot_required_file
    - name: Reboot the server (if required).
      ansible.builtin.reboot: null
      when: reboot_required_file.stat.exists == true
    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: 'yes'

# to do: server:
# install wordpress, setup website kevwells.com
# set up data volume network shares
# configure security groups aws


- hosts: laptops
  gather_facts: 'yes'
  become: 'yes'
  tasks:
    - name: install brave-browser dependencies
      ansible.builtin.apt:
        name: apt-transport-https curl 
        state: present

    - name: Download gpg keys
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg

    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
        state: present

##  gpk keys:
## curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

# add the repo:
## echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"

# apt install brave-browser


    - name: install brave-browser 
      ansible.builtin.apt:
        name: 
        state: present

    - name: install terminator
      ansible.builtin.apt:
        name: terminator
        state: present
    - name: install virtualization system
      ansible.builtin.apt:
        name: cpu-checker
        state: present
    - name: install qemu-kvm
      ansible.builtin.apt:
        name: qemu-kvm
        state: present
    - name: Copy /home/kevin/shellscripts/ folder
      ansible.builtin.copy:
        src: /home/kevin/shellscripts/
        dest: /home/kevin/shellscripts/
        owner: kevin
        group: kevin
        mode: '0644'
    - name: install libvirt-clients
      ansible.builtin.apt:
        name: libvirt-clients
        state: present 
    - name: install libvirt-daemon-system
      ansible.builtin.apt:
        name: libvirt-daemon-system
        state: present
    - name: install bridge-utils
      ansible.builtin.apt:
        name: bridge-utils
        state: present
#next,start the kvm services and enable 
#systemctl enable libvirtd
# systemctl start libvirtd
## but above state: present  . could be enough, since we do not want to auto start these services, only start manually when needed

# add your desired user to the KVM and libvirt groups:
# usermod -aG kvm $USER
# usermod -aG libvirt $USER


## to do : laptops:

# install brave browser
# dependencies: 
# apt install apt-transport-https curl
##  gpk keys:
# curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

# add the repo:
 ## echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"

# apt install brave-browser



