---

- hosts: all
  become: true
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 

#---
 #- hosts: all 
  # become: yes
   #become_method: sudo
  # tasks:
   #  - name: "Update Repository cache"
    #   apt:
     #  update_cache: true
   #    cache_valid_time: 3600
    #   force_apt_get: true

   - name: Display the last line of the previous task to check the stats
     debug:
     msg:  "{{updatesys.stdout_lines|last}}"

